---
kind: pipeline
type: digitalocean
#type: docker
name: default

token:
  from_secret: token

platform:
  os: linux
  arch: amd64
  #arch: arm64

server:
  #image: ubuntu-20-04-x64
  image: ubuntu-18-04-x64
  #image: debian-10-x64
  #image: centos-7-x64
  #image: fedora-33-x64
  size: s-1vcpu-1gb
  #size: s-1vcpu-2gb
  #size: s-2vcpu-2gb
  #size: s-2vcpu-4gb
  region: sfo3

steps:
- name: build
  #image: geerlingguy/docker-ubuntu1604-ansible:latest
  #image: geerlingguy/docker-ubuntu1804-ansible:latest
#  image: geerlingguy/docker-ubuntu2004-ansible:latest
#  pull: if-not-exists
  commands:
  #- apt-mark hold linux-image-generic linux-headers-generic
  - apt-get -y -qq update
  - apt-get -y -qq upgrade
  - apt-get -y -qq install ansible python3 python3-pip python3-venv
  - ansible-playbook install.yml

trigger:
  branch:
  - main
  event:
  - push